# Generated by Django 5.2.3 on 2025-06-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional short description of the service.')),
                ('icon_class', models.CharField(blank=True, help_text='Optional icon or emoji.', max_length=50)),
            ],
        ),
    ]
