# Generated by Django 5.2.3 on 2025-06-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_attached_washroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='rent',
            field=models.PositiveIntegerField(default=5500, help_text='Monthly rent in INR'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Optional icon or emoji', max_length=50),
        ),
    ]
